### ISSUE TITLE
can.Component should show a warning if tag name is missing a hyphen - P(3) ~3

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-component#11]
From: https://github.com/canjs/canjs/issues/1541

**Comment by pYr0x** [comment]
@justinbmeyer should this issue not be solved on canjs/can-view-callbacks https://github.com/canjs/can-view-callbacks/blob/master/can-view-callbacks.js#L40-L44 ?
or how can i add a warning on canjs/can-component

**Comment by justinbmeyer** [comment]
Yeah, you're probably right, it should be done in callbacks.
