### ISSUE TITLE
Warn if viewModel: DefineMap is used ~3

### ISSUE THREAD

**Issue by matthewp** [canjs/can-component#14]
When using can-define we need to specify the Component ViewModel using `ViewModel: Map` with a **capital V**.  We could warn if using a lower-case V with a can-define/map/map, it's an easy mistake to make and hard to know what you did wrong.

**Comment by marshallswain** [comment]
![screen shot 2016-07-17 at 8 04 23 pm](https://cloud.githubusercontent.com/assets/128857/16904818/bfd8e31e-4c59-11e6-8453-748e747a1f5e.jpg)

Yes.  This caught me up for ~30 minutes, today.

**Comment by justinbmeyer** [comment]
Isn't that a different thing?

**Comment by marshallswain** [comment]
@justinbmeyer, it sure looks like it should be.  That's the error I get when I use `viewModel` instead of `ViewModel` in a `can-component`.

**Comment by justinbmeyer** [comment]
Both work now.  But a warning would still be good.

**Comment by bgando** [comment]
### The following gives a warning in dev env:
dev.warn("Assigning a DefineMap type to the viewModel property may not be what you intended. Did you mean ViewModel instead? More info: https://canjs.com/doc/can-component.prototype.ViewModel.html")
```
var vm = DefineMap.extend({...});
Component.extend({
  viewModel: vm
});
```
### The following is does not give a warning:
```
var vm = DefineMap.extend({...});
Component.extend({
  ViewModel: vm
});

Component.extend({
  viewModel: function(){...}
});
```

**Comment by phillipskevin** [comment]
I think we want to use `canReflect. isConstructorLike` for this to differentiate between constructor's and other functions.

**Comment by matthewp** [comment]
Yeah, regular functions are ok to pass as viewModel, I think, just not typed ones.
