### ISSUE TITLE
Component automount

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-component#159]
I would like to add a `autoMount` property like:

```js
can.Component.extend({
  autoMount: true,
  tag: "some-thing",
  view: stache("hi there")
})
```

Once attached, this component will immediately look for `<some-thing>` elements in the page that have no `viewModel`.  It will then "take over" that element.

Furthermore, `autoMount: true` components will monitor elements being inserted into the page.  If a `<some-thing>` element that has no `viewModel` is inserted, it will "take over" that element.

Another example:

```html
<my-counter/>
<script>
var CounterVM = can.DefineMap.extend("CounterVM",{
  count: {value: 0, type: "number"},
  add: function(){
    this.count++;
  }
})

can.Component.extend({
  tag: "my-counter",
  autoMount: true,
  ViewModel: CounterVM,
  view: can.stache(`
        <span>{{count}}</span>
        <button on:click="add()">+1</button>
  `)
});
</script>
```

Other names:

- `autorender`
- `selfMount`
- `mount`

If there is `HTML` within the component, we will throw an error saying "unsupported" for right now.  In the future, we can use this for the `<content>` tag's content.

**Comment by justinbmeyer** [comment]
Other ideas:

- standalone, headless, orphan
- foreign, outside, far
- disjoint
- unmanaged

**Comment by BigAB** [comment]
- `addToDOM: true`
- `DOMactive: true`
- `upgradeDOM: true`
- `activeDOM: true`
-  `activateElements: true`
- `inDOM: true`
- `elementUpgrade: true`

**Comment by frank-dspeed** [comment]
@pYr0x https://github.com/canjs/can-element/issues/39

this works with stache bindings will prepare also a ssr variant that will replace existing content. to allow first inital render in under 2ms

**Comment by frank-dspeed** [comment]
@justinbmeyer 
All This solves autorender autoMount. and is cross browser via webcomponents.js

# Steal Related WebComponents 
- https://github.com/stealjs/steal/issues/1309
- https://github.com/at-nikolaus/steal-element
- https://github.com/at-nikolaus/steal-module-element

# CanJS Related WebComponents
- https://github.com/at-nikolaus/can-stache-template
- https://github.com/at-nikolaus/can-stache-element will get merged with template
- https://github.com/at-nikolaus/can-route-element
  - Interristing app entry point based on can-element replaces can-route but could use can-route
- many more but don't cleaned it all up will talk about that at a other spot only wanted to make you aware of that in this context.
All This solutions don't require can-component and are creating more a donejs-app so a main integration point

**Comment by justinbmeyer** [comment]
@frank-dspeed Can you please write up _clearly_ what these proposals contain?

**Comment by justinbmeyer** [comment]
Closing as this is already in 4.0.
