### ISSUE TITLE
Proposal: can-component CanJS 4 version defineElement

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-component#173]
I would love to see that can-component replaces automount via document.customElement.define()

At present autoMount is a Polyfill for web components up coming https://www.w3.org/TR/custom-elements/#custom-elements-api

for registering auto rendering element instances  i would love to unify as much of the code as possible and so stay 100% spec compatible as javascript allows setting properties on elements i would love to see canjs also doing that.

can-component can use document.customElement.define() to register a component tag as self domData registering element that then gets rendered via canjs nativ methods that are using the already right named callbacks :+1: connectedCallback disconnectedCallback

so it turns can-component into can-component-element a nativ WebComponent

@justinbmeyer 

## Concept
property autoMount at present does scan the document via can-each for its component tag then registers the found elements in can-dom-data-state via can-utils domData 

i saw this also using a new Key Value Storage called can-global that adds again a extra dependency that i don't understand as from a higher level point of view we have the ability to store data nativ to the element it self including its rendering methods and all its state as javascript propertys

i think that allows us a more isolated clean way to store state.

location is importent i saw this property gets set in can-global and retrived from there.

## Explain why location is importent
the location and all other script execution meta data gets really importent as soon as you switch plattform like running in web service worker context or in Microsoft https://en.wikipedia.org/wiki/Chakra_(JScript_engine) not to be confused with https://en.wikipedia.org/wiki/Chakra_(JavaScript_engine)
It will also now more often happen that you run same code in diffrent engines at the same time as the service worker is only a little little example and steal has currently already path issues that we can solve more well when we don't use any location related stuff i have a upcoming steal pr that is not really well explained that will show how to us tar.gz with a nativ file tree as bundle with nativ browser methods we need steal only to form the graph's
- https://github.com/stealjs/steal/issues/1306 Linked here only for completeness 

## Details about different javascript engines
There are upcoming new static compiling JavaScript Engines as also the nativ EMCA specification is on its way to be more trace able and static compile able if needed 

## Short Conclusion
There will be new kind of complexity for JavaScript frameworks like your that did implement a lot of Polyfill for this nativ upcoming stacks that solve the same problems right. I simply would love to get CanJS so lean that it is simply a Cross Compatible way to archive results like with nativ WebComponents. Lets Say i want that CanJS replaces Google Ploymer as its easy able to do that and with much cleaner and better code. As Also the view Engine abstraction with the Observe ables and soon Symbols and Proxys is awsome but i don't need to tell you that you know your awsome.

Then i want to long term expand on that and factor as polymer does nativ canJS components like can-ui a jquery ui replacement that uses as selectors can-view engine so in current most case stache all that needs to be WebComponents and CanJS Compatible.

i want that CanJS is the core for all event stuff and binding stuff only so that it extends nativ WebComponent Stack well and brings in the Observations and fast callback stuff.@justinbmeyer 

## Concept
property autoMount at present does scan the document via can-each for its component tag then registers the found elements in can-dom-data-state via can-utils domData 

i saw this also using a new Key Value Storage called can-global that adds again a extra dependency that i don't understand as from a higher level point of view we have the ability to store data nativ to the element it self including its rendering methods and all its state as javascript propertys

i think that allows us a more isolated clean way to store state.

location is importent i saw this property gets set in can-global and retrived from there.

## Explain why location is importent
the location and all other script execution meta data gets really importent as soon as you switch plattform like running in web service worker context or in Microsoft https://en.wikipedia.org/wiki/Chakra_(JScript_engine) not to be confused with https://en.wikipedia.org/wiki/Chakra_(JavaScript_engine)
It will also now more often happen that you run same code in diffrent engines at the same time as the service worker is only a little little example and steal has currently already path issues that we can solve more well when we don't use any location related stuff i have a upcoming steal pr that is not really well explained that will show how to us tar.gz with a nativ file tree as bundle with nativ browser methods we need steal only to form the graph's
- https://github.com/stealjs/steal/issues/1306 Linked here only for completeness 

## Details about different javascript engines
There are upcoming new static compiling JavaScript Engines as also the nativ EMCA specification is on its way to be more trace able and static compile able if needed 

## Short Conclusion
There will be new kind of complexity for JavaScript frameworks like your that did implement a lot of Polyfill for this nativ upcoming stacks that solve the same problems right. I simply would love to get CanJS so lean that it is simply a Cross Compatible way to archive results like with nativ WebComponents. Lets Say i want that CanJS replaces Google Ploymer as its easy able to do that and with much cleaner and better code. As Also the view Engine abstraction with the Observe ables and soon Symbols and Proxys is awsome but i don't need to tell you that you know your awsome.

Then i want to long term expand on that and factor as polymer does nativ canJS components like can-ui a jquery ui replacement that uses as selectors can-view engine so in current most case stache all that needs to be WebComponents and CanJS Compatible.

i want that CanJS is the core for all event stuff and binding stuff only so that it extends nativ WebComponent Stack well and brings in the Observations and fast callback stuff.

**Comment by justinbmeyer** [comment]
Can you take another pass explaining this?  Using proper punctuation and spelling will help. 

Also explaining more what you mean by location. I assume you mean something like a realm. Why is location important?

**Comment by frank-dspeed** [comment]
@justinbmeyer 

## Concept
property autoMount at present does scan the document via can-each for its component tag then registers the found elements in can-dom-data-state via can-utils domData 

i saw this also using a new Key Value Storage called can-global that adds again a extra dependency that i don't understand as from a higher level point of view we have the ability to store data nativ to the element it self including its rendering methods and all its state as javascript propertys

i think that allows us a more isolated clean way to store state.

location is importent i saw this property gets set in can-global and retrived from there.

## Explain why location is importent
the location and all other script execution meta data gets really importent as soon as you switch plattform like running in web service worker context or in Microsoft https://en.wikipedia.org/wiki/Chakra_(JScript_engine) not to be confused with https://en.wikipedia.org/wiki/Chakra_(JavaScript_engine)

## Details about diffrent javascript engines
There are upcoming new static compiling JavaScript Engines as also the nativ EMCA specification is on its way to be more trace able and static compile able if needed 

## Short Conclusion
There will be new kind of complexity for javascript frameworks like your that did implament a lot of Polyfill for this nativ upcoming stacks that solve the same problems right. I simply would love to get CanJS so lean that it is simply a Cross Compatible way to archive results like with nativ WebComponents. Lets Say i want that CanJS replaces Google Ploymer as its easy able to do that and with much cleaner and better code.

Then i want to long term expand on that and factor as polymer does nativ canJS components like can-ui a jquery ui replacement that uses as selectors can-view engine so in current most case stache

i want that CanJS is the core for all event stuff and binding stuff only so that it extends nativ WebComponent Stack well and brings in the Observations and fast callback stuff.

**Comment by frank-dspeed** [comment]
Created a upcoming issue: https://github.com/canjs/can-component/issues/174

**Comment by frank-dspeed** [comment]
@matthewp https://developer.mozilla.org/de/docs/Web/API/HTMLScriptElement

**Comment by frank-dspeed** [comment]
@matthewp also watch in the examples of that API there you see our new steal add script tags import method ;)

**Comment by justinbmeyer** [comment]
@frank-dspeed I'm not sure what this was requesting.  I'm going to close it.  I'll re-open if the language can get cleaned up a bit so I can make sense of it.  Thanks!

**Comment by frank-dspeed** [comment]
its good that this is closed all is hornored and splitted up into seperated pr's
