### ISSUE TITLE
Validate tag names

### ISSUE THREAD

**Issue by matthewp** [canjs/can-component#18]
In order to eventually achieve https://github.com/canjs/can-component/issues/10 we should start validating tag names and throw if they use an invalid name. Would like to get this in to 3.0 since it's a breaking change.

**Comment by matthewp** [comment]
Thoughts @justinbmeyer @pYr0x @daffl ?  We could make an option to turn it off for backwards compat if needed.

**Comment by pYr0x** [comment]
@matthewp what do you mean be "validating"? 
we have added this in 3.0 https://github.com/canjs/can-view-callbacks/pull/6

**Comment by matthewp** [comment]
Ok, will take the discussion there.
