### ISSUE TITLE
4.0: inserted events don't work without importing 

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-component#191]
In 4.0, `inserted` events (and others) don't work in components unless you run this code yourself:

```
import domEvents from "can-dom-events";
import domMutateDomEvents from "can-dom-mutate/dom-events";

domEvents.addEvent(domMutateDomEvents.inserted);
```

Shouldn't `can-component` do this? cc @andrejewski @chasenlehara.

**Comment by andrejewski** [comment]
I don't think so. We are trying to get everyone on to dis/connectCallback for what inserted/removed provide, at least this is my understanding.

**Comment by phillipskevin** [comment]
Ok, then maybe it just needs to be added to the migration guide.

**Comment by phillipskevin** [comment]
I added this to the migration guide issues.
