### ISSUE TITLE
Show require statements in all the code examples

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-component#196]
Some of the code examples / signatures don’t include the require statements for variables such as Component or DefineMap, which makes it unclear where those are coming from.

**Comment by justinbmeyer** [comment]
I’m not sure we should set this precedent. There should probably be some base level assumptions about what these variables mean.

**Comment by phillipskevin** [comment]
Since DefineMap and stache are now the defaults I think we should remove the variables instead of showing where to import them from.
