### ISSUE TITLE
Enter event dosen't  work

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-component#227]
The enter event dosen't work on custom tag element when ```can-component``` is used as individual package like in this example:
```js
import Component from 'can-component';

Component.extend({
  tag: 'x-enter',
  view: '<input type="text" />',
  events: {
    '{element} enter': function() {
      alert('Entered');
    }
  }
})
```
However it works when the global ```can``` is used like in this [jsbin](http://jsbin.com/wovazaw/2/edit?html,js,output)
I tried to import ```can-event-dom-enter``` but it causes versions conflict with ```can-dom-data-state```

**Comment by justinbmeyer** [comment]
Which version of enter are you installing?

**Comment by cherifGsoul** [comment]
@justinbmeyer after ```npm ls can-event-dom-enter``` here is the output:
```
 can-component@4.0.4
  └─┬ can-util@3.11.5
    └── can-event-dom-enter@1.0.4
```

**Comment by justinbmeyer** [comment]
You need to install enter in your own deps, instead of getting it implicitly from can-util. Does that work?

**Comment by cherifGsoul** [comment]
It dosen't work!!
here is my use case https://github.com/cherifGsoul/can-places-autocomplete/blob/upgrade-donejs/src/places-autocomplete/places-autocomplete-events.js#L6 

https://github.com/cherifGsoul/can-places-autocomplete/blob/upgrade-donejs/src/places-autocomplete/places-autocomplete-events.js#L67

**Comment by cherifGsoul** [comment]
Close this in favor of https://github.com/canjs/canjs/issues/4064

**Comment by matthewp** [comment]
Hey @cherifGsoul, I updated the migration guide to explain how to do this: https://canjs.com/doc/migrate-4.html . Search for "enter event". Let me know if you still have issues!

**Comment by cherifGsoul** [comment]
@matthewp Great! Thanks a lot I updated my code yesterday and it works I didn't saw the page which explains how ```can-event-dom-enter``` before.
