### ISSUE TITLE
Make can-component templating language neutral ~13

### ISSUE THREAD

**Issue by matthewp** [canjs/can-component#23]
Currently it assumes you are using stache and sets up stache-style bindings (depending on `can-stache-bindings`). It would be better if instead the template provided an api to set up the bindings.

**Comment by justinbmeyer** [comment]
This could be part of `tagData`.

**Comment by matthewp** [comment]
Good idea, what should this look like? Something like:

```js
tagData = {
  ...

  setupBinding: function(el, callback, initialData){
    ...
    return function teardownBindings() { ... }
  }
};
```

Mimicking what's already happening [here](https://github.com/canjs/can-component/blob/3deb15bc2c1b30a911d6c39abec1b29fd3511afe/can-component.js#L119).  stache would then provide this function on tagData and depend on stacheBindings itself.

**Comment by matthewp** [comment]
This works already.
