### ISSUE TITLE
Error on click handler bound to viewModel

### ISSUE THREAD

**Issue by IcculusC** [canjs/can-component#27]
View model and component look like this
```javascript
let viewModel = DefineMap.extend({
  user: {
    value: Object,
    Type: User
  },
  clickHandler: function() {
    do something;
  }
});

Component.extend({
  tag: "my-component",
  template: myStache,
  ViewModel: viewModel
});
```

Example stache template
```
<button type="button" ($click)="clickHandler()">Click Me!</button>
```

clicking the button produces this error
```
Uncaught TypeError: expr.hash is not a function
  handler @ can-stache-bindings.js:329
```

**Comment by eben-roux** [comment]
I'm no genius with canjs but what is `DefineMap`?

usually the following seems to work (off the top of my head here):

```
let viewModel = can.Map.extend({
    define: {
        // define stuff here
    },
    clickHandler: function() {
        // do something
    }
})
```

It may be that in the original code the `clickHandler` is part of the `define` hash.  That may be causing the issue.

Let me know if I'm totally off track here.

**Comment by marshallswain** [comment]
@eben-roux define-map is new.  it allows the same traditional Observable benefits of can.Map, but you get to use the normal dot `.` operator for property access.  It will be the new standard Map type in CanJS 3.0.

@IcculusC I don't see anything wrong with that code.  What version of can-component are you using?

**Comment by IcculusC** [comment]
```
    "can-component": "^3.0.0-pre.14",
    "can-connect": "^0.5.5",
```

**Comment by IcculusC** [comment]
@marshallswain after digging around in can-stache-bindings and can-stache I believe this bug is related to an assumption about the type of a particular variable in can-stache-bindings, I've recreated this in the simplest case on a completely fresh environment, should I close this and create a new one over in that repo?

**Comment by marshallswain** [comment]
Yeah, just reference this issue, please, so we can maintain the link.  Thanks for your diligence!

**Comment by IcculusC** [comment]
@marshallswain looks like a fix for this was committed this morning with https://github.com/canjs/can-stache-bindings/commit/adf1de292604bf759989d0b13ad0d1b07fc2d35f

**Comment by IcculusC** [comment]
fixed by https://github.com/canjs/can-stache-bindings/releases/tag/v3.0.0-pre.9
