### ISSUE TITLE
"DefineMap is undefined" error in doc/can-component.prototype.helpers.html

### ISSUE THREAD

**Issue by CODE-REaD** [canjs/can-component#273]
The Demo tab in https://canjs.github.io/next/doc/can-component.prototype.helpers.html, is blank.  Here is the error shown in my browser's console:

> TypeError
> ​columnNumber: 4
> ​fileName: "https://canjs.github.io/next/node_modules/steal/steal.js line 3526 > eval"
> ​lineNumber: 15
> ​message: "DefineMap is undefined"
> ​onModuleExecution: true
> ​stack: "execute@<Anonymous:15:4\n\t"
> 

I was able to run the code as-is in JSBin by loading <script src="https://unpkg.com/can/dist/global/can.js"> rather than the bundle used in https://github.com/canjs/canjs/blob/master/demos/can-component/selected.html, so I suspect that is the problem.
____
BTW, if someone is editing this, [it would be helpful](https://forums.donejs.com/t/generic-property-names-confuse-the-beginner/908/1) to use something other than `ViewModel` as the name of the ViewModel being referenced.  Just name it `aViewModel` and I'll be happy :-) :

    ViewModel = can.DefineMap.extend({
        selected: {
            Default: can.DefineList
        },
        toggle: function(item){
            var selected = this.selected,
                index = selected.indexOf(item);

            if( index >= 0 ) {
                selected.splice(index, 1);
            } else {
                selected.push(item);
            }
        }
    });

    can.Component.extend({
        tag: "my-items",
        ViewModel: ViewModel,
        view: can.stache.from("demo-html"),

**Comment by chasenlehara** [comment]
Everything on the `/next/` website is bound to be broken; I’d stick to canjs.com for now.
