### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-component#301]
As part of https://github.com/canjs/canjs/issues/4116, we also might want to make some docs less prominent by either hiding them or moving them to a `deprecated` section:

- [ ] [events](https://canjs.com/doc/can-component.prototype.events.html)
- [ ] [helpers](https://canjs.com/doc/can-component.prototype.helpers.html)
- [ ] [viewModel](https://canjs.com/doc/can-component.prototype.view-model.html)
- [ ] [leakScope](https://canjs.com/doc/can-component.prototype.leakScope.html) ?

Also, we should
- [ ] move [beforeremove](https://canjs.com/doc/can-component/beforeremove.html) under `lifecycle hooks`

And probably
- [ ] support a `connectedCallback` directly on a component's prototype
- [ ] support a `beforeRemove` directly on a component's prototype

**Comment by phillipskevin** [comment]
@justinbmeyer do you think these things should be deprecated officially? Meaning we'll remove them in the next major.

**Comment by phillipskevin** [comment]
I think the best way to do this is to move these into mixins and then move the current docs to a "legacy" section or something that links to the docs to the mixins.

I'm going to investigate what it will take to make that work.

**Comment by chasenlehara** [comment]
Closing this because the docs have been moved to a new “deprecated” section.
