### ISSUE TITLE
`value` broken with pre.15

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-component#31]
It might be deeper than just `value` being broken.  The template doesn't really update.

This simple component doesn't update (in response to data changes) with pre.15.
```js
import Component from 'can-component';
import DefineMap from 'can-define/map/';
import './account-list.less';
import template from './account-list.stache';
import Account from 'example-app/models/account';

export const ViewModel = DefineMap.extend({
  allAccounts: {
    Type: Account.List,
    value: []
  }
});

export default Component.extend({
  tag: 'account-list',
  ViewModel: ViewModel,
  template
});
```

```hbs
<h3>All Accounts</h3>
{{allAccounts.length}}
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {{#each allAccounts as account}}
      <tr>
        <td><a href="javascript://" ($click)="edit(.)">{{name}}</a></td>
        <td>{{type}}</td>
        <td><button href="javascript://" ($click)="account.destroy()">delete</button></td>
      </tr>
    {{/each}}
  </tbody>
</table>
```

With pre.14, {{allAccounts.length}} shows 0, as expected.  With pre.15 it shows nothing.  If I do 

```js
allAccounts.replace([{
  name: 'Checking'
}]);
```
it doesn't update the template.  If I do 

```js
allAccounts = new Account.List([{
  name: 'Checking'
}]);
```
it doesn't update the template.

Downgrading to pre.14 makes everything work as expected.

(Just in case you think you're seeing double, I accidentally opened this in can-define, originally: https://github.com/canjs/can-define/issues/51)

**Comment by matthewp** [comment]
I think this is probably a can-define bug, cc @justinbmeyer.  I think lower-case value should be given values and capital Value should be a list definition.

**Comment by matthewp** [comment]
In this particular case you are asking that all instances of your component share the same Array, is this your intent @marshallswain ?

**Comment by marshallswain** [comment]
No, that's not my intent, and I always do that.  😢

**Comment by matthewp** [comment]
You probably want to do either:

```js
Value: DefineList 
```

Which creates a new DefineList for each VM instance.

Or:

```js
{
  value: function() {
    return [];
  }
}
```

That creates a new array for each instance.

**Comment by marshallswain** [comment]
Thanks.  I always remember this after things start acting weird.  :)

**Comment by marshallswain** [comment]
I tried another attribute:

```js
account: {
    Type: Account,
    value() {
      return {
        name: '',
        type: 'Checking'
      };
    }
  },
```

```hbs
<input type="text" name="name" value="" {($value)}="account.name" ($enter)="save(account)">
<select type="select" name="name" value="" {($value)}="account.type">
  {{#each accountTypes}}
    <option>{{name}}</option>
  {{/each}}
</select>
<button ($click)="save(account)">Save</button>
<button ($click)="reset()">Reset</button>
```

I get the following error saying that account is not defined:
![screen shot 2016-08-24 at 10 10 18 am](https://cloud.githubusercontent.com/assets/128857/17938407/0a7560c2-69e3-11e6-8744-a145da0eff48.jpg)

**Comment by justinbmeyer** [comment]
@marshallswain can you create a test?  Thanks.

**Comment by marshallswain** [comment]
@justinbmeyer I added a test [here](https://github.com/canjs/can-component/pull/32) that updates to the latest can-define and it's working, so I'm closing this to figure out what's creating the issue in my project.
