### ISSUE TITLE
ViewModel: {} is borked

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-component#33]
if I do something like:

```
Component.extend({
  ViewModel: {
    someMethod: function(){

    }
  }
});
```

`someMethod` won't be available on the view model because:

https://github.com/canjs/can-component/blob/master/can-component.js#L75

`this.ViewModel = types.DefaultMap.extend(vmName,protoViewModel);`

should be 

`this.ViewModel = types.DefaultMap.extend(vmName,this.prototype.ViewModel);`

**Comment by Sinjhin** [comment]
Fixed by #34
