### ISSUE TITLE
component.constructor.ViewModel is undefined when "viewModel" is function (v3.3.10)

### ISSUE THREAD

**Issue by YuriChupyrkin** [canjs/can-component#332]
Hello canJS team.

I migrate the APP from canJs 2 to canJs 3 and have issue connected to `can-component` package.

I use `can-component` **v3.3.10**
When I use **viewModel** as **function**, I have exception in that line:

https://github.com/canjs/can-component/blob/f22db4daa5cdeaa2fdeee44187e473f6de242d75/can-component.js#L277

It happens because ```component.constructor.ViewModel``` is **undefined**.

Looks like that issue is fixed in **v4.5.0**:
https://github.com/canjs/can-component/blob/7f8e9b62c4318d7cb3a53c892b58e02150faf2e9/can-component.js#L512

Could you fix it for `can-component` **v3.x.x**?

![Screen Shot 2019-03-27 at 11 53 17](https://user-images.githubusercontent.com/4204416/55063024-349d2900-5088-11e9-8f70-147fb8b01175.png)

@justinbmeyer  please take a look

**Comment by justinbmeyer** [comment]
> When I use viewModel as function, I have exception in that line

What does this mean? What does your component look like?

**Comment by iSokrat** [comment]
@justinbmeyer Example below (docs - https://v2.canjs.com/docs/can.Component.prototype.viewModel.html):

```js
  //can v2:
  import {baseViewModel} from 'path/to/file';

  // ...

  can.Component.extend({
     // ... fields ...
     viewModel(attrs, parentVM, element) {
          
           // preparing data

           return baseViewModel.extend({
               field: parentVM.attr('someField')
           });
     }
  })
```

**Comment by YuriChupyrkin** [comment]
@justinbmeyer ,  take a look at example

```
export default can.Component.extend({
  tag: 'my-component',
  template: can.stache(template),
  leakScope: true,
  viewModel: function (attrs, parentViewModel) {
   ....
  },
});
```

**Comment by cherifGsoul** [comment]
@YuriChupyrkin , @iSokrat this is fixed and released!

**Comment by iSokrat** [comment]
@cherifGsoul Thanks!
