### ISSUE TITLE
Add deprecation notices to the deprecated docs

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-component#336]
All of these pages should have a deprecation notice:

- https://canjs.com/doc/can-component/beforeremove.html
- https://canjs.com/doc/can-component/content.html
- https://canjs.com/doc/can-component.prototype.events.html
- https://canjs.com/doc/can-component.prototype.helpers.html
- https://canjs.com/doc/can-component.prototype.leakScope.html
- https://canjs.com/doc/can-component.prototype.view-model.html

The deprecation notice should have the can-component version in which they were deprecated, a note about what APIs replace them, and ideally links to the migration guides for more information.

**Comment by cherifGsoul** [comment]
After discussion with @phillipskevin on `Slack` about the `events` replacements he suggested the add a section on events on the main Component docs and mention:
* normal DOM events
* “delegated” DOM events
* ViewModel events
* lifecycle events (inserted/removed)

Once is published we can add link to this page in the deprecation notice.
