### ISSUE TITLE
Implement slot-like replacement for `<content select>` ~40

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-component#4]
From: https://github.com/canjs/canjs/issues/2278
- Also https://github.com/canjs/canjs/issues/2429 - specify scope or context

Background on slots:

https://webkit.org/blog/4096/introducing-shadow-dom-api/
https://www.w3.org/TR/shadow-dom/#distributions
https://www.w3.org/TR/shadow-dom/#dfn-slot-element
# content && template-NAME
## Example 1

Shadow DOM:

```
  <b>Name</b>:
  <content name="fullName">
      <content name="firstName"></content>
      <content name="lastName"></content>
  </content><br>
  <b>Email</b>: <content name="email">Unknown</content><br>
  <b>Address</b>: <content name="address">Unknown</content>
```

User DOM:

```
<my-contact>
  <title-template><span>Commit Queue</span></title-template>
  <email-template><a href="mailto:commit-queue@webkit.org">commit-queue@webkit.org</a></email-template>
  <address-template><span>One Infinite Loop, Cupertino, CA 95014</span></address-template>
</my-contact>
```

**Comment by rjgotten** [comment]
FYI; I have something like this already implemented on top of `can.Component` in 2.3.x though it resembles how named regions work in ASP.NET MVC's Razor template engine.

In my case, you include `<can-region>` tags inside a component class's template and inside a component instance's content. `<can-region>` elements inside the content are lifted out (removed) and used to fill up placeholder `<can-region>` elements inside the component class's template.

For example...

Shadow DOM:
```
<b>Name</b>:
<section class="panel">
  <header class="toolbar toolbar--offright">
    <can-region name="toolbar" />
  </header>
  <content />
</section>
```

User DOM:
```
<ui-panel>
  <can-region name="toolbar">
    <button ($click)="switchMode()">{{mode}}</button>
  </can-region>

  {{#is mode 'edit'}}
    <label>Name: <input {($value)}="name" /></label>
    <label>Email: <input {($value)}="email" /></label>
  {{#else}}
    <b>Name:</b> {{name}}<br />
    <b>Email:</b> {{name}}<br />
  {{/is}}
</ui-panel>
```

So you get a mix of content that remains in the main content area and content which is moved elsewhere. The whole thing is implemented as a pair of tag helpers woven into the component's template renderer and the `componentTagData.subtemplate` renderer.

They communicate via access to a shared `can.Map` that holds references to the subtemplates and re-uses part of the implementation for partials to be live bound to the subtemplate changing.

Have a look at this gist for my implementation, maybe you'll find it good enough to use:
https://gist.github.com/rjgotten/346eafd0893f5801b2fba653b198002e

**Comment by justinbmeyer** [comment]
We probably need to be able to pass the scope:


```
<paginate-grid {connection}="todoConnection">

    <header-template>
        <tr><td>Name</td><td>Owner</td></tr>
    </header-template>

    <body-template>
        <tr><td>{{name}}</td><td>{{owner.name}}</td>
    </body-template>

</paginate>


<table>
    <thead>
        <content name="header"/>
    </thead>
    <tbody>
        {{#each todoConnection.getList({}).value}}
            <content name="body" scope="."/>
        {{/each}}
    </tbody>
</table>
```
