### ISSUE TITLE
Document limitations with using custom elements inside tables

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-component#55]
Since [you can't use custom elements inside of tables](http://forums.donejs.com/t/can-component-use-in-html-tables/466/4), it’d be helpful to have this documented.

**Comment by justinbmeyer** [comment]
Is this a limitation of browsers in general?

**Comment by chasenlehara** [comment]
Yeah, I don’t think the HTML spec allows other elements inside a (assumed) `tbody`, so it’s not just a limitation of CanJS. I think it’s still helpful to document though, since it [gets](http://forums.donejs.com/t/can-component-use-in-html-tables/466) [asked](https://github.com/canjs/canjs/issues/1799) from time to time.
