### ISSUE TITLE
Content extension test failing in IE11

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-component#69]
[This test](https://github.com/canjs/can-component/blob/master/test/component-map-test.js#L971-L992) is failing in IE11 with the following error:

```
Expected:  "inner-tag TEMPLATE inner-tag CONTENT outer-tag CONTENT"
 
Result:  "innerinnerouter-tag CONTENTtag CONTENT <content></content>tag TEMPLATE <content></content>"
 
```

**Comment by justinbmeyer** [comment]
reminds me of https://github.com/canjs/can-view-target/pull/19

**Comment by phillipskevin** [comment]
The `can-view-target` issue with `cloneNode` actually only happens after calling a `stache` renderer function that includes a `can-component`. That means that when `can-view-target` loads in IE11, the [`clonesWork`](https://github.com/canjs/can-view-target/blob/master/can-view-target.js#L37-L60) variable is `true`, but something breaks `cloneNode` before this content extension test runs.

Here is the most minimal example I have:


```js
var stache = require('can-stache');
var Component = require('can-component');

function isCloneNodeBroken(){
  var el = document.createDocumentFragment();
  el.appendChild(document.createTextNode('abc-xyz'));
  var clone = el.cloneNode(true);
  return clone.childNodes.length === 1;
}

Component.extend({
  tag: 'foo-bar',
  view: function() {
    isCloneNodeBroken(); // true
    return document.createDocumentFragment();
  }
});

isCloneNodeBroken(); // false
stache('<foo-bar />')();
isCloneNodeBroken(); // true
```

**Comment by phillipskevin** [comment]
This is the root cause: https://github.com/canjs/can-view-target/issues/18#issuecomment-267866897.

**Comment by phillipskevin** [comment]
Fixed by thttps://github.com/canjs/can-view-target/pull/29.
