### ISSUE TITLE
simpleHelpers on components

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-component#89]
I think `helpers` on components is currently mostly pointless.  It's hard to test, and helpers always get called with computes.

I propose a `simpleHelpers` object on Components like:

```
MyComponent = Component.extend({
  simpleHelpers: {
    toYear: function(date){
      return date.getYear()
    }
  }
})
```

To test, these should be available a property on the Component

```js
MyComponent.simpleHelpers.toYear( new Date() ) //-> 2017
```

**Comment by justinbmeyer** [comment]
Also, it would be good if the helpers could accept an array of helpers:

```
helpers: [
  require("can-stache-helper-pack"),
  require("my-project/lib/helpers")
]
```

**Comment by justinbmeyer** [comment]
Really these should be part of the template:

```
<can-import from="can-stache-helper-pack" SOMEHOW-MIXIN/>
```

**Comment by rjgotten** [comment]
> I think `helpers` on components is currently mostly pointless

Component-specific helpers are **very** useful if you want to perform operations in the view that are based on state of a component and its view model that is semi-internal and which should not be reachable from the outside.

I have a rather complex component that handles virtualized rendering for large data sets in the 10,000 of items worth, which uses component-specific helpers for just this reason.

**Comment by justinbmeyer** [comment]
Closing.  We suggest using `ViewModel` methods for this now.
